### PR TITLE
Fix/new test structure

### PR DESCRIPTION
**Pull request by cb-mega**
This restructures our tests in:
- unit tests
- integration tests
- tools
- python tests

This is done for QMake, CMake, and autoconf.
Once this code makes it to develop we need to adjust a few Jenkins jobs.

### CODE REVIEW

**Comment by mattw-mega** [comment]
It's quite a big rearrangement - just trying to see where the main SDK tests went, they seem to be in SdkTest_test.cpp now, but it's lost all its history?

**Comment by cb-mega** [comment]
It's a rename: `tests/sdk_test.cpp → tests/integration/SdkTest_test.cpp` so history should be preserved. Note that I followed the standard naming scheme where the test file contains the name of the test sute.

**Comment by polmr** [comment]
trigger compilation

**Comment by cb-mega** [comment]
@polmr It won't run successfully on jenkins currently because the test executables have moved. E.g. Unit tests are now at `tests/test_unit` when built with autotools. Once this change makes it to develop we'll have to adjust jenkins.

**Comment by mattw-mega** [comment]
Having found the right setting to 'follow renames', the change is pretty straightforward - I'll approve it.

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Pull request merged**
