### PR TITLE
Changes for MEGAcmd-1.2.0 NAS build.

### PR DESCRIPTION
**Pull request by dwmega**
Changes as follows:
- Updated the version of many build dependencies.
-- Simplified build_sdk as some upstream bugs no longer exist.
-- Tried to match versions contained in vcpkg as much as possible.
- Fixed minor issue with configure script.
-- Check for OpenSSL would fail on some platforms.
-- Issue hit (potentially) due to newer OpenSSL which seems to reference symbols in pthreads.

### CODE REVIEW

**Comment by aabellagm** [comment]
trigger compilation

**Comment by sergiohs84** [comment]
@dwmega closing this PR, as you say:
> No longer necessary as fixed upstream.
Please, feel free to reopen if needed. Thanks

**Comment by dwmega** [comment]
@sergiohs84 It's unfortunate that the comments were detached from the files they were originally present in.

That comment, regarding something being fixed upstream, was meant in the context of a particular like in build_sdk.sh not being necessary. It did mean that the entire changeset was unnecessary.

**Comment by mattw-mega** [comment]
Yes this branch is needed - We've built the Synology and QNAP MEGAcmd 1.2 release against the current head of this branch - to be tagged if they accept the packages.  I'll reopen the PR, thanks

**Comment by sergiohs84** [comment]
Please, @polmr , have a quick look. You are the master of the building script.
We can proceed if all seems fine ;)

**Pull request merged**
