### PR TITLE
WIP: Update bindings (Obj-C)

### PR DESCRIPTION
**Pull request by javisanesp**

### CODE REVIEW

**Comment by javisanesp** [comment]
Please, @sergiohs84 and @jnavarrom review and mergue, whenever you can.

**Comment by javiserrano** [comment]
`this` in the callback belongs to the intermediate layer and is deleted in `removeMEGAXXXDelegate()` functions (it's not managed by the garbage collector). So keeping `this` instead of `this->listener` would cause problems if the pointer has been already deleted. A possible solution would be to queue the deletion of those listeners using `dispatch_async`.

**Comment by brookskhan** [comment]
Rigan can

**Comment by javisanesp** [comment]
Somehow deprecated, so closing it 🙂

**Pull request closed without merging**
