### PR TITLE
Feature5445 send contacts files

### PR DESCRIPTION
**Pull request by alber2510**
Send contacts and files. Feature #5445
- Add new MegaNode to MegaNodeList
- Return MegaClient from MegaApi

trigger compilation

### CODE REVIEW

**Comment by alber2510** [comment]
trigger compilation

**Comment by polmr** [comment]
trigger compilation

**Comment by alber2510** [comment]
trigger compilation

**Comment by sergiohs84** [comment]
This PR needs to be created for `develop` instead of `master`

**Pull request closed without merging**
