### PR TITLE
Fix build with FFMPEG 5

### PR DESCRIPTION
**Pull request by Vascom**
This change allow to build with FFMPEG 5.0.

### CODE REVIEW

**Comment by ChrisLane** [comment]
Have you not found that you need to also remove [this line](https://github.com/meganz/sdk/blob/b7e9a4d32e2dbaffa8831cc7122afe22a30cdb0b/src/gfx/freeimage.cpp#L305) to allow compilation with current builds of ffmpeg?

**Comment by ChrisLane** [comment]
The line was linked in my comment. https://github.com/meganz/sdk/blob/b7e9a4d32e2dbaffa8831cc7122afe22a30cdb0b/src/gfx/freeimage.cpp#L305

It causes this compile error: https://github.com/meganz/sdk/issues/2576

**Comment by Vascom** [comment]
May be it need for latest release. I used 3.9.6.b to build megasync 4.6.5.0.

**Comment by Vascom** [comment]
Agree. Need to remove this line.
It was done in other place of my spec-file to build megasync.

**Review by ChrisLane — APPROVED** [review]

**Comment by sl1pkn07** [comment]
now, with ffmpeg 6, `AV_CODEC_CAP_TRUNCATED` is deprecated and removed

https://github.com/FFmpeg/FFmpeg/commit/dd846bc4a9163f875cc2c4e99325c1a7b4ab8e7d

**Comment by sl1pkn07** [comment]
patch for ffmpeg6

https://github.com/meganz/sdk/issues/2635#issuecomment-1495405085

**Comment by drmikecooke** [comment]
Came across this using Bookworm debian which has ffmpeg 5.

commenting out referenced line and converting the the line 316

[code]
AVCodec* decoder = avcodec_find_decoder(codecId);
[/code]

to 

[code]
const AVCodec* decoder = avcodec_find_decoder(codecId);
[/code]

also _seemed_ to be required.

for it to get past this and move on to other work (not finished yet)

**Comment by sergiohs84** [comment]
Already integrated in the current codebase. Thanks

**Pull request closed without merging**
