### PR TITLE
Release/v3.3.9

### PR DESCRIPTION
**Pull request by javiserrano**
- Asynchronous GFX layer
- Support for libraw in the GFX layer based on QT
- 2-factor authentication
- Improvements to build megacli with VIsual Studio and without readline
- Get the avatar from a contact link
- New commands to keep Camera Uploads alive
- New logic for connections with waitd
- Allow to disable all graphic features
- Bug fixes and other minor improvements

### CODE REVIEW

**Comment by shinchiro** [comment]
Hello, I'm trying to build this PR with mingw and megacli getting segfault when typing anything on console:

```
megacli.exe caused an Access Violation at location 000000000042A78A in module megacli.exe Reading from location 0000000000000000.

AddrPC           Params
000000000042A78A 0000000000000000 00000000008033D0 0000000000809B68  megacli.exe!checkevents  [/mnt/c/base/build_gcc8/packages/megasdk-prefix/src/megasdk/src/megaclient.cpp @ 2759]
000000000042B259 00000000006F2D10 00000000006F2CF0 000000000504FD50  megacli.exe!wait  [/mnt/c/base/build_gcc8/packages/megasdk-prefix/src/megasdk/src/megaclient.cpp @ 2499]
000000000040F298 0000000000000000 0000000001010101 00000000059C19A0  megacli.exe!megacli  [/mnt/c/base/build_gcc8/packages/megasdk-prefix/src/megasdk/examples/megacli.cpp @ 6014]
00000000006E6440 0000000000000000 000000000000003E 0000000000809C98  megacli.exe!main  [/mnt/c/base/build_gcc8/packages/megasdk-prefix/src/megasdk/examples/megacli.cpp @ 6140]
00000000004013A5 0000000000000000 0000000000000000 0000000000000000  megacli.exe!__tmainCRTStartup  [/mnt/c/base/build_gcc8/toolchain/mingw-w64-prefix/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 331]
000000000040150B 0000000000000000 0000000000000000 0000000000000000  megacli.exe!mainCRTStartup  [/mnt/c/base/build_gcc8/toolchain/mingw-w64-prefix/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 215]
00007FFDFDBC3034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFDFE691551 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
```

**Comment by polmr** [comment]
@shinchiro , does this branch fix that? https://github.com/meganz/sdk/tree/gfxfix

**Comment by shinchiro** [comment]
Yes, that fix the segfault.

Also I wonder why after typing `killsession all`, megacli still listed all previous session. This doesn't happen with previous version

**Comment by polmr** [comment]
trigger compilation

**Pull request merged**
