### PR TITLE
Workaround for a crash in Android

### PR DESCRIPTION
**Pull request by javiserrano**
It needs testing to ensure that it works properly

### CODE REVIEW

**Comment by jraragon** [comment]
`********** Crash dump: **********
Build fingerprint: 'google/hammerhead/hammerhead:5.0/LRX21O/1570415:user/release-keys'
pid: 3293, tid: 3293, name: acy.android.app  >>> mega.privacy.android.app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Stack frame #00 pc 0003a5d4  /system/lib/libc.so (tgkill+12)
Stack frame #01 pc 00016af5  /system/lib/libc.so (pthread_kill+52)
Stack frame #02 pc 00017707  /system/lib/libc.so (raise+10)
Stack frame #03 pc 00013f75  /system/lib/libc.so (__libc_android_abort+36)
Stack frame #04 pc 00012a3c  /system/lib/libc.so (abort+4)
Stack frame #05 pc 0022604b  /system/lib/libart.so (art::Runtime::Abort()+170)
Stack frame #06 pc 000a72e9  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
Stack frame #07 pc 000b1401  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1112)
Stack frame #08 pc 000b1945  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
Stack frame #09 pc 000b33df  /system/lib/libart.so (art::ScopedCheck::CheckInstance(art::ScopedCheck::InstanceKind, _jobject*)+374)
Stack frame #10 pc 000b3d4b  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckEbPKcz.constprop.128+514)
Stack frame #11 pc 000b6e33  /system/lib/libart.so (art::CheckJNI::NewObjectV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+54)
Stack frame #12 pc 0004b3a7  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so (_JNIEnv::NewObject(_jclass*, _jmethodID*, ...)+16): Routine _JNIEnv::NewObject(_jclass*, _jmethodID*, ...) at /home/jraragon/adt-bundle/ndk/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/jni.h:588
Stack frame #13 pc 0004c309  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so (SwigDirector_MegaLogger::log(char const*, int, char const*, char const*)+152): Routine SwigDirector_MegaLogger::log(char const*, int, char const*, char const*) at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/java_wrap.cxx:953
Stack frame #14 pc 000651ff  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so: Routine mega::ExternalLogger::log(char const*, int, char const*, char const*) at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/sdk/src/megaapi_impl.cpp:14423
Stack frame #15 pc 000ac405  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so: Routine mega::SimpleLogger::~SimpleLogger() at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/sdk/src/logging.cpp:66
Stack frame #16 pc 0006b943  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so: Routine mega::ExternalLogger::postLog(int, char const*, char const*, int) at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/sdk/src/megaapi_impl.cpp:14399 (discriminator 1)
Stack frame #17 pc 0006b983  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so: Routine mega::MegaApiImpl::log(int, char const*, char const*, int) at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/sdk/src/megaapi_impl.cpp:3757
Stack frame #18 pc 00059613  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so: Routine mega::MegaApi::log(int, char const*, char const*, int) at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/sdk/src/megaapi.cpp:1300
Stack frame #19 pc 00053d0d  /data/app/mega.privacy.android.app-3/lib/arm/libmega.so (Java_nz_mega_sdk_megaJNI_MegaApi_1log_1_1SWIG_11+60): Routine Java_nz_mega_sdk_megaJNI_MegaApi_1log_1_1SWIG_11 at /home/jraragon/MEGA/StudioProjects/android2DEVELOP/app/src/main/jni/mega/java_wrap.cxx:9875
Stack frame #20 pc 002778f9  /data/dalvik-cache/arm/data@app@mega.privacy.android.app-3@base.apk@classes.dex`

Develop: a2ee2d5e7e7499dbbae8c88fcb95a1ef57039804
`git fetch origin
git checkout -b fix-crash-android origin/fix-crash-android
git merge develop`

**Comment by javiserrano** [comment]
It should work in all cases now.

**Comment by javiserrano** [comment]
Ready to review

**Comment by jraragon** [comment]
Tested and working in:
Android 4.0
Android 4.4
Android 5.0
Android 6.0
Android 7.1

Merging.

**Pull request merged**
